#define		    VOID	1
#define		    VAR		2
#define 	    CONST	3
#define		    IF		4
#define		    ELSE	5
#define 	    WHILE	6
#define		    READ	7
#define         PRINT       8
#define         CLOSEBRA    9
#define         OPENBRA     10
#define         ID          11
#define         INTLITERAL  12
#define         LPAREN      13
#define         RPAREN      14
#define         SEMICOLON   15
#define         COMMA       16
#define         ASSIGNOP    17
#define         PLUSOP      18
#define         MINUSOP     19
#define 		MULOP	20
#define 		DIVOP	21
#define 		STRLITERAL 22
